$background = rgb(16142B)
$foreground = rgb(BBB9D1)
$color0 = rgb(46483A)
$color1 = rgb(2F2A5D)
$color2 = rgb(585D2A)
$color3 = rgb(625A9A)
$color4 = rgb(9C6A6A)
$color5 = rgb(90839E)
$color6 = rgb(929A5A)
$color7 = rgb(9693B5)
$color8 = rgb(69677F)
$color9 = rgb(3E387C)
$color10 = rgb(767C38)
$color11 = rgb(8378CD)
$color12 = rgb(D08D8D)
$color13 = rgb(C0AED2)
$color14 = rgb(C2CD78)
$color15 = rgb(9693B5)
