foreground         #B0B1B6
background         #0A0B10
cursor             #AC9CA9

active_tab_foreground     #0A0B10
active_tab_background     #B0B1B6
inactive_tab_foreground   #B0B1B6
inactive_tab_background   #0A0B10

active_border_color   #B0B1B6
inactive_border_color #0A0B10
bell_border_color     #161823

color0      #242926
color1		#161823
color2		#161822
color3		#232116
color4		#4D505E
color5		#7E6676
color6		#667E6E
color7		#86878E
color8		#5E5E63
color9		#1E202E
color10		#1E202E
color11		#2E2C1E
color12		#676A7E
color13		#A8889D
color14		#88A893
color15		#86878E
